# Generated by Django 5.2 on 2026-01-18 02:28

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("published_at", models.DateTimeField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768, null=True, blank=True)),
            ],
        ),
    ]
